import {
  Activity, ArrowUpRight, Ban, Bike, BrainCircuit, Bug, Camera, Cloud, CodeXml, Compass,
  CreditCard, Cpu, Database, FileText, Film, Fingerprint, Gamepad2, Gem, Globe, Hammer,
  Laptop, Layers3, Mail, MapPin, Microchip, Paintbrush, PaintRoller, PanelsTopLeft, Radio,
  Server, ShieldCheck, ShoppingBag, Terminal, Trophy, UserRoundCog, Wind, Wrench,
} from "lucide-react";

const icons = {
  "fa-hat-cowboy": ShieldCheck,
  "fa-laptop-code": Laptop,
  "fa-brain": BrainCircuit,
  "fa-code": CodeXml,
  "fa-html5": CodeXml,
  "fa-css3-alt": CodeXml,
  "fa-js": CodeXml,
  "fa-react": Activity,
  "fa-node": Server,
  "fa-wind": Wind,
  "fa-database": Database,
  "fa-layer-group": Layers3,
  "fa-terminal": Terminal,
  "fa-gem": Gem,
  "fa-python": CodeXml,
  "fa-window-maximize": Laptop,
  "fa-microchip": Microchip,
  "fa-envelope": Mail,
  "fa-envelope-open": Mail,
  "fa-credit-card": CreditCard,
  "fa-cloud": Cloud,
  "fa-globe": Globe,
  "fa-server": Server,
  "fa-google": Globe,
  "fa-git-alt": CodeXml,
  "fa-gitlab": CodeXml,
  "fa-hard-drive": Database,
  "fa-windows": PanelsTopLeft,
  "fa-image": Paintbrush,
  "fa-table": Layers3,
  "fa-file-word": FileText,
  "fa-paint-brush": Paintbrush,
  "fa-fly": Activity,
  "fa-paint-roller": PaintRoller,
  "fa-buromobelexperte": Layers3,
  "fa-key": ShieldCheck,
  "fa-user-tie": UserRoundCog,
  "fa-ban": Ban,
  "fa-hamsa": ShieldCheck,
  "fa-fingerprint": Fingerprint,
  "fa-steam": Gamepad2,
  "fa-palette": Paintbrush,
  "fa-raspberry-pi": Cpu,
  "fa-lightbulb": Activity,
  "fa-motorcycle": Bike,
  "fa-film": Film,
  "fa-camera": Camera,
  "fa-mug-hot": ShoppingBag,
  "fa-compass": Compass,
  "fa-hammer": Hammer,
  "fa-file-pdf": FileText,
  "fa-trophy": Trophy,
  "fa-usb": Microchip,
  "fa-satellite-dish": Radio,
  "fa-bug": Bug,
  "fa-arrow-up-right-from-square": ArrowUpRight,
  "fa-mug-saucer": ShoppingBag,
  "fa-bolt": Activity,
  "fa-tools": Wrench,
  gimp: Paintbrush,
};

export default function Icon({ name, size = 18, className = "", ...props }) {
  const IconComponent = icons[name] ?? CodeXml;
  return <IconComponent aria-hidden="true" size={size} className={className} {...props} />;
}
